name: CI Pipeline

# Trigger the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: pytest test_main.py