name: CI Pipeline
# Trigger the workflow on push or pull request events

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
     mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 30s 
          --health-timeout 10s 
          --health-retries 10 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest test_main.py
